
import java.awt.Dimension;
import java.io.FileWriter;
import javax.swing.JFrame;
import java.io.BufferedWriter;
import java.io.File;
import java.util.HashMap;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import java.awt.Color;
import java.util.List;import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.json.JSONArray;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Mateusz
 */
public class NewJPanel extends javax.swing.JPanel {
    
    
    
    
    String name, surname, city, address, login, password, rePassword, sex, email, phoneNumber, pesel, postCode;
   // Account person;
     JFrame F = new JFrame("Panel");
     Border empty = BorderFactory.createLineBorder(Color.RED, 1);
     Border correct = BorderFactory.createLineBorder(Color.gray, 1);
     final static String outputFilePath
        = "D:\\Własne\\Programowanie\\Repozytorium\\bankapp\\src\\main\\java\\accounts.json";
     
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        //ErrorLabelScrol.setBackground(new Color(238,238,238, 255));
        ErrorPane.setBackground(new Color(238,238,238, 255));
        ErrorPanel.setBackground(new Color(238,238,238, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JTabbedPane();
        LogiIn = new javax.swing.JPanel();
        Login_Label = new javax.swing.JLabel();
        Login_Field = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Password_label = new javax.swing.JPasswordField();
        Register = new javax.swing.JPanel();
        Last_Name = new javax.swing.JTextField();
        First_Name = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        PostCode = new javax.swing.JTextField();
        FirstName_Label = new javax.swing.JLabel();
        LastName_Label = new javax.swing.JLabel();
        City_Label = new javax.swing.JLabel();
        Address_Label = new javax.swing.JLabel();
        PostCode_Label = new javax.swing.JLabel();
        Phone_Number = new javax.swing.JTextField();
        PhoneNumber_Label = new javax.swing.JLabel();
        Sex_Text = new javax.swing.JLabel();
        Sex_box = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pesel_label = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Login_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Email_label = new javax.swing.JTextField();
        Password_Name = new javax.swing.JLabel();
        RePassword_Name = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        RePassword = new javax.swing.JPasswordField();
        ErrorPane = new javax.swing.JScrollPane();
        ErrorPanel = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 400));

        MainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainPanel.setInheritsPopupMenu(true);
        MainPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        MainPanel.setName(""); // NOI18N
        MainPanel.setPreferredSize(new java.awt.Dimension(500, 100));

        LogiIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogiIn.setMinimumSize(new java.awt.Dimension(500, 200));

        Login_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Login_Label.setText("Login");
        Login_Label.setToolTipText("");

        Login_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_FieldActionPerformed(evt);
            }
        });

        Password_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Password_Label.setText("Password");
        Password_Label.setToolTipText("");

        Login.setText("Login");

        javax.swing.GroupLayout LogiInLayout = new javax.swing.GroupLayout(LogiIn);
        LogiIn.setLayout(LogiInLayout);
        LogiInLayout.setHorizontalGroup(
            LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogiInLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Login_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Login_Label))
                    .addComponent(Password_Label, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Password_label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );
        LogiInLayout.setVerticalGroup(
            LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogiInLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Login_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.addTab("Log In", null, LogiIn, "");

        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.setMinimumSize(new java.awt.Dimension(500, 500));

        Last_Name.setAutoscrolls(false);
        Last_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        First_Name.setAutoscrolls(false);
        First_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        First_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_NameActionPerformed(evt);
            }
        });

        City.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        Address.setAutoscrolls(false);
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        PostCode.setAutoscrolls(false);
        PostCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        FirstName_Label.setText("First Name");

        LastName_Label.setText("City");

        City_Label.setText("Last Name");

        Address_Label.setText("Address");

        PostCode_Label.setText("Post Code");

        Phone_Number.setAutoscrolls(false);
        Phone_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        PhoneNumber_Label.setText("Phone number");

        Sex_Text.setText("Sex");
        Sex_Text.setToolTipText("");

        Sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female", " " }));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesel");

        Pesel_label.setAutoscrolls(false);
        Pesel_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel2.setText("Login");

        Login_field.setAutoscrolls(false);
        Login_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel3.setText("E-mail");

        Email_label.setAutoscrolls(false);
        Email_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        Password_Name.setText("Password");

        RePassword_Name.setText("Repeat password");

        Password.setAutoscrolls(false);
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        RePassword.setAutoscrolls(false);
        RePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ErrorPane.setBorder(null);

        ErrorPanel.setEditable(false);
        ErrorPanel.setBorder(null);
        ErrorPanel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ErrorPanel.setAutoscrolls(false);
        ErrorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ErrorPane.setViewportView(ErrorPanel);

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName_Label)
                    .addComponent(LastName_Label)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PostCode_Label)
                    .addComponent(PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex_Text)
                    .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Login_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Name)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(City_Label)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Label)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber_Label)
                    .addComponent(Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Pesel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePassword_Name)
                    .addComponent(RePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ErrorPane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(FirstName_Label)
                    .addComponent(City_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastName_Label)
                    .addComponent(Address_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PostCode_Label)
                    .addComponent(PhoneNumber_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_Text)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Pesel_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Login_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePassword_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorPane, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        MainPanel.addTab("Register", null, Register, "");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
        );

        MainPanel.getAccessibleContext().setAccessibleName("form");
        MainPanel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void First_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_NameActionPerformed

    //Button register
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        try {
            //TEST
            System.out.println("Test dzień 999");
            HashMap<String, String> dataFromFile = checkIfDataExist();
            System.out.println("dataFromFile: ");
            System.out.println(dataFromFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
       
        
        
        
        // TODO add your handling code here:
        //String getName, getSurname, city, address, login, password, rePassword, sex;
        //int phoneNumber, pesel, postCode;
        
        //Set standard border color
        
        ErrorPanel.setForeground(Color.red);
        
        //ArrayList<String> errorList = new ArrayList<String>();
        String errorList = "";
        ErrorPanel.setText("");
        /*
        StyledDocument documentStyle = ErrorPanel.getStyledDocument();
        SimpleAttributeSet centerAttribute = new SimpleAttributeSet();
        StyleConstants.setAlignment(centerAttribute, StyleConstants.ALIGN_LEFT);
        documentStyle.setParagraphAttributes(0, documentStyle.getLength(), centerAttribute, false);
        */
        
        First_Name.setBorder(correct);
        Last_Name.setBorder(correct);
        City.setBorder(correct);
        Address.setBorder(correct);
        Login_field.setBorder(correct);
        Password.setBorder(correct);
        RePassword.setBorder(correct);
        Email_label.setBorder(correct);
        Sex_box.setBorder(correct);
        Phone_Number.setBorder(correct);
        Pesel_label.setBorder(correct);
        PostCode.setBorder(correct);
        
        
        name = First_Name.getText();
        surname = Last_Name.getText();
        city = City.getText();
        address = Address.getText();
        login = Login_field.getText();
        password = Password.getText();
        rePassword = RePassword.getText();
        email = Email_label.getText();
        sex = String.valueOf(Sex_box.getSelectedItem());
        
        phoneNumber = Phone_Number.getText();
        pesel = Pesel_label.getText();
        postCode = PostCode.getText();
        
        //System.out.println("Login: " + login);
        //System.out.println("Email: " + email);
        //System.out.println("phoneNumber: " + phoneNumber);
        List<Account> loadData = null;
        try{
            loadData = loadData();
            for(Account userData : loadData){
                //System.out.println("User Login: " + userData.getLogin());
                //System.out.println("User Email: " + userData.getEmail());
                //System.out.println("User PhoneNumber: " + userData.getPhoneNumber());
                if((userData.getLogin().equals(login))){
                    Login_Field.setBorder(empty);
                    errorList += " Login Already Exist!" + "\n";
                    //ErrorLabel.setText("Login Already Exist!");
                    //System.out.println("Login exist!");
                    //return;
                } 
                if(userData.getEmail().equals(email)){
                    //ErrorLabel.setText("Email Already Exist!");
                    errorList += "Email Already Exist!" + "\n";
                    Email_label.setBorder(empty);
                   //System.out.println("Email exist!");
                    //return; 
                }
                if(userData.getPhoneNumber().equals(phoneNumber)){
                    //ErrorLabel.setText("Phone Number Already Exist!");
                    errorList += "Phone Number Already Exist!" +"\n";
                    Phone_Number.setBorder(empty);
                    //System.out.println("PhoneNumber exist!");
                    //return;
                } 
            }
            
        } catch (Exception e) {
        }
        
         
        
        
       // person = new Account(name, surname, city, address, login, password, sex, email,
        //        phoneNumber, pesel, postCode);
        
        
        ArrayList<JTextField> accountData = new ArrayList<JTextField>();
            accountData.add(First_Name);
            accountData.add(Last_Name);
            accountData.add(City);
            accountData.add(Address);
            accountData.add(Login_field);
            accountData.add(Password);
            accountData.add(RePassword);
            accountData.add(Email_label);
            accountData.add(Phone_Number);
            accountData.add(Pesel_label);
            accountData.add(PostCode);
        
        BufferedWriter bf = null;
        
        
        
         //Save data to file
         try{
             
            JsonObject obj = new JsonObject();
            JSONArray arr = new JSONArray();
             //System.out.println("1");
            File file = new File(outputFilePath);
          // System.out.println("2");


          
          
            obj.addProperty("name", name);
            obj.addProperty("surname", surname);
            obj.addProperty("city", city);
            obj.addProperty("address", address);
            obj.addProperty("login", login);
            obj.addProperty("password", password);
            obj.addProperty("sex", sex);
            obj.addProperty("email", email);
            obj.addProperty("phoneNumber", phoneNumber);
            obj.addProperty("pesel", pesel);
            obj.addProperty("postCode", postCode);
          
           // System.out.println("3");

            //check if data are corrected
            
            
            String checkDataErrorList = checkData(First_Name, Last_Name, City, Address, Login_field, Password, RePassword, Email_label, Phone_Number, Pesel_label, PostCode);
            // System.out.println("4");
            //check if Login is longer than 8 
             System.out.println("Errors!: " + checkDataErrorList);
            if(login.length() < 8){
                if(!login.isEmpty()){
                    errorList+= "Login Is Too Short!" + "\n";
                }
                
                //ErrorLabel.setText("Login Is Too Short!");
                Login_field.setBorder(empty);
            }
            //System.out.println("5");
            
            
            for(JTextField data : accountData){
                if(data.getBorder() == empty){
                    ErrorPanel.setText(ErrorPanel.getText() + errorList + checkDataErrorList);
                    return;
                }
                
            }
            ErrorPanel.setForeground(Color.green);
            ErrorPanel.setText("Account creation successful!");
            loadData.add(new Account(name, surname, city, address, login, password, email, sex, phoneNumber, pesel, postCode));
            
            arr.put(obj);
            
            //System.out.println("6");
            bf = new BufferedWriter(new FileWriter(file));
            Gson gson = new GsonBuilder().setPrettyPrinting().create();

            /*
            
            Type type = new TypeToken<Map<String, Entry>>() {}.getType();
            String fileName = "src/test/java/org/example/diary/test.json";
            Reader reader = new FileReader(new File(fileName));
            Map<String, Entry> diary = gson.fromJson(reader, type);
            diary.get("2019-01-13").setTextfield1("modified field");
            Entry e = new Entry();
            e.setDate("2019-01-14");
            e.setScale(3);
            e.setTextfield1("Dear Diary");
            e.setTextfield1("I met a ...");
            diary.put(e.getDate(), e);
            FileWriter fw = new FileWriter(new File(fileName + ".out.json"));
            gson.toJson(diary, fw);
            fw.close();
            
            */
           
            //JsonElement account = gson.toJsonTree(person);
           // System.out.println("7");
           //JSONArray ja = new JSONArray();
           //ja.put(obj);
            gson.toJson(loadData, bf);
            System.out.println("Data Saved!");

            bf.flush();
           // System.out.println("8");
            //System.out.println("Data saved!");
            

            //file.close();
        }catch(Exception e) {
            System.out.println("ERROR!!!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /*
    public  HashMap<String, String> checkIfDataExist() throws FileNotFoundException{
        System.out.println("DZIAŁA!");
        //Gson gson = new Gson();
            System.out.println("1");
            BufferedReader bufferedReader = new BufferedReader(new FileReader(outputFilePath));
System.out.println("2");
            Gson gson = new Gson();
            System.out.println("3");
            HashMap<String, String> json = gson.fromJson(bufferedReader, HashMap.class);
            System.out.println("file data: ");
            System.out.println(json);
            return json;
        
    }
    */
    
    
    private void Login_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_FieldActionPerformed

    public static List<Account> loadData(){
        
        List<Account> data = null;
        
        try {
            //System.out.println("Data loaded");
           File file = new File(outputFilePath);
           // System.out.println("1");
           Gson gson = new Gson();
          // System.out.println("1");
           BufferedReader bf = new BufferedReader(new FileReader(file));
            //JsonReader reader = new JsonReader(new FileReader("D:\\Własne\\Programowanie\\Repozytorium\\bankapp\\src\\main\\java\\accounts.json"));
           // System.out.println("2");
            
            //Type type = new TypeToken<Map<String, String>>(){}.getType();
            //Map<String, String> myMap = gson.fromJson(reader, type);
             //System.out.println("2");
            Type userType = new TypeToken<List<Account>>(){}.getType(); 
            //System.out.println("3");
            data = gson.fromJson(bf, userType);
  // System.out.println("4");
        
        } catch (Exception e) {
            System.out.println("ERROR DATA LOAD!");
             e.printStackTrace();
        }
        
        

        
        return data;
    }
    
    
    public String checkData(JTextField name, JTextField surname, JTextField city, JTextField address, JTextField login, 
            JPasswordField password, JPasswordField rePassword, JTextField email, JTextField phoneNumber, JTextField pesel, JTextField postCode){
            //Border empty = BorderFactory.createLineBorder(Color.RED, 1);
            //Border correct = BorderFactory.createLineBorder(Color.gray, 1);

            String errorList = "";
            
            ArrayList<JTextField> accountData = new ArrayList<JTextField>();
            accountData.add(name);
            accountData.add(surname);
            accountData.add(city);
            accountData.add(address);
            accountData.add(login);
            accountData.add(password);
            accountData.add(rePassword);
            accountData.add(email);
            accountData.add(phoneNumber);
            accountData.add(pesel);
            accountData.add(postCode);
            
            boolean fieldIsEmpty = false;
            //Check if field is empty
            for(JTextField data : accountData){
                if(data.getText().isEmpty()){
                    fieldIsEmpty = true;
                    //ErrorLabel.setText("Some Field Is Empty!");
                    data.setBorder(empty);
                    //System.out.println("Is Empty" + data);
                }
            }
            
            if(fieldIsEmpty){
                errorList += "All fields must be completed" +"\n";
            }
            
            //check if Pesel contains only numbers and length is equal 11
            String peselError = isDigit(pesel, 11, "pesel");
            
            //check if phone number contains only numbers and length is equal 9
            String phoneNumberError = isDigit(phoneNumber, 9, "phone number");
            
            //check if password is the same like rePassword
           // System.out.println("Password: " + String.valueOf(password.getPassword()) + " | " + "RePassword" + String.valueOf(rePassword.getPassword()));
            if(!String.valueOf(password.getPassword()).equals(String.valueOf(rePassword.getPassword()))){
                errorList += "Password and rePassword Must Be The Same!" + "\n";
                //ErrorLabel.setText("Password and rePassword Must Be The Same!");
                password.setBorder(empty);
                rePassword.setBorder(empty);
                //System.out.println("Password is not equal rePassword");
            }
            
            //check if password contain one special char, one big letter, one digit and is longer than 8
            String checkPasswordError = checkPassword(password);
                
            Pattern postCodeOne = Pattern.compile("[0-9]{5}");
            //System.out.println("Postcode: " + postCode.getText());
            //Matcher matchPostCodeOne = postCodeOne.matcher(postCode.getText());
            boolean matchPostCodeOne = Pattern.matches("[0-9]{5}", postCode.getText());
            System.out.println("PostCode text: " + postCode.getText());
            if(!matchPostCodeOne){
                postCode.setBorder(empty);
                if(!postCode.getText().isEmpty()){
                    errorList += "Post Code Is Invalid!" + "\n";
                }
                
               // ErrorLabel.setText("Post Code Is Invalid!");
                //System.out.println("Match postCode not exist!");
            }
            
            //Pattern emailPattern = Pattern.compile("^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$");
            String emailPattern = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
            //Matcher matchEmail = emailPattern.matcher(email.getText());
            boolean matchEmail = Pattern.matches(emailPattern, email.getText());
            if(!matchEmail){
                
                email.setBorder(empty);
                if(!email.getText().isEmpty()){
                    errorList += "Email Is Invalid!" +"\n" ;
                }
                //.setText("Email Is Invalid!");
                //System.out.println("Match email not exist!");
            }
            errorList += checkPasswordError + peselError + phoneNumberError;
            return errorList;
            
    }
    
    public String checkPassword(JPasswordField password){
        boolean upperCase = false;
        boolean lowerCase = false;
        boolean digit = false;
        boolean specialChar = false;
        
        String correctPassword = "The password should contain:" + "\n" +
                                    " * At least one uppercase and lowercase letter" + "\n" +
                                    " * Should be greater than or equal to 6" + "\n" +
                                    " * Should contain at least one number" + "\n" +
                                    " * Should contain at least one special character" ;
        
        String tooShort = "Password is too short!" +"\n";
        
        String text = password.getText();
        System.out.println("Check Password!");
        if(text.length() < 8){
            if(!text.isEmpty()){
                return tooShort;
            }
            System.out.println("Password is too short!");
            return "";
        }
        
        for(int i = 0; i < text.length(); ++i){
            if(Character.isDigit(text.charAt(i))){
                digit = true;
            }
            if(Character.isUpperCase(text.charAt(i))){
                upperCase = true;
            }
            if(Character.isLowerCase(text.charAt(i))){
                lowerCase = true;
            }
            if(!Character.isDigit(text.charAt(i))
               && !Character.isLetter(text.charAt(i))
               && !Character.isWhitespace(text.charAt(i))){
               
                specialChar = true;           
            }
        }
        
        
                                      
        
        if(upperCase && digit && specialChar && lowerCase){
            System.out.println("Password is correct!");
            password.setBorder(correct);
            return "";
        }else{
            //System.out.println("Bad password");
            //ErrorLabel.setText(ErrorLabel.getText() + correctPassword + "\n");
            password.setBorder(empty);
            return correctPassword;
        }
    }
    
    
    // Method allow to check if every char in str is digit and length of str is equal length
    public String isDigit(JTextField str, int length, String name){
        String errorList = "";
        if(str.getText().length() !=  length){
                //System.out.println("Length is not equal " + length);
                
                str.setBorder(empty);
                if(!str.getText().isEmpty()){
                    errorList += "Length in " + name +" must be equal " + length + "\n";
                }
            }
            for(int i = 0; i < str.getText().length(); ++i){
                char checkChar = str.getText().charAt(i);
                if(!Character.isDigit(checkChar)){
                    errorList += "Field should contain only digits" + "\n";
                    //System.out.println("Char is not digit");
                    str.setBorder(empty);
                }
            }
            return errorList;
    }
    
   
    public void createGUI(){
        F.setMinimumSize(new Dimension(500,500));
        F.setPreferredSize(new Dimension(500,500));
        F.add(MainPanel);
        F.setVisible(true);
        String getName = Login_Field.getText();
        System.out.println("Text: " + getName);
    }
    

    
    //  "D:\\Własne\\Programowanie\\Repozytorium\\bankapp\\src\\main\\java\\accounts.json"
    
    public static void testFileRead(){
        try {
    // create Gson instance
           // System.out.println("1");
    Gson gson = new Gson();
//System.out.println("2");
    // create a reader
    Reader reader = Files.newBufferedReader(Paths.get("D:\\Własne\\Programowanie\\Repozytorium\\bankapp\\src\\main\\java\\accounts.json"));
//System.out.println("3");
    // convert JSON file to map
    Map<?, ?> map = gson.fromJson(reader, Map.class);
//System.out.println("4");
    // print map entries
    for (Map.Entry<?, ?> entry : map.entrySet()) {
        System.out.println(entry.getKey() + "=" + entry.getValue());
    }

    // close reader
    reader.close();

} catch (Exception ex) {
    ex.printStackTrace();
}
        

    }

   
    public static void main(String[] args) {

        Gson gson = new Gson();
        NewJPanel N = new NewJPanel();
        N.setPreferredSize(new Dimension(500,500));
        //N.setMinimumSize(new Dimension(650,470));
        N.createGUI();
         
        //String getName, getSurname, city, address, login, password, rePassword, sex;
        //int phoneNumber, pesel, postCode;
        
        
        
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Address_Label;
    private javax.swing.JTextField City;
    private javax.swing.JLabel City_Label;
    private javax.swing.JTextField Email_label;
    private javax.swing.JScrollPane ErrorPane;
    private javax.swing.JTextPane ErrorPanel;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField First_Name;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JPanel LogiIn;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Login_Field;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JTextField Login_field;
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JLabel Password_Name;
    private javax.swing.JPasswordField Password_label;
    private javax.swing.JTextField Pesel_label;
    private javax.swing.JLabel PhoneNumber_Label;
    private javax.swing.JTextField Phone_Number;
    private javax.swing.JTextField PostCode;
    private javax.swing.JLabel PostCode_Label;
    private javax.swing.JPasswordField RePassword;
    private javax.swing.JLabel RePassword_Name;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel Sex_Text;
    private javax.swing.JComboBox<String> Sex_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

/*

        name = First_Name.getText();                    JTextField
        surname = Last_Name.getText();                  JTextField
        city = City.getText();                          JTextField
        address = Address.getText();                    JTextField
        login = Login_field.getText();                  JTextField
        password = Password_label.getText();            JTextField
        rePassword = RePassword_label.getText();        JTextField
        
        phoneNumber = Phone_Number.getText();           JTextField
        pesel = Pesel_label.getText();                  JTextField
        postCode = PostCode.getText();                  JTextField  

*/