
import java.awt.Dimension;
import java.io.FileWriter;
import javax.swing.JFrame;
import org.json.JSONObject;
import com.google.gson.Gson;
import java.io.BufferedWriter;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import java.awt.Color;
import java.awt.List;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.border.Border;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Mateusz
 */
public class NewJPanel extends javax.swing.JPanel {
    String name, surname, city, address, login, password, rePassword, sex, email, phoneNumber, pesel, postCode;
    Account person;
     JFrame F = new JFrame("Panel");
     Border empty = BorderFactory.createLineBorder(Color.RED, 1);
     Border correct = BorderFactory.createLineBorder(Color.gray, 1);
     final static String outputFilePath
        = "D:\\Własne\\Repozytorium_CV\\bankapp\\src\\main\\java\\accounts.json";
     
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JTabbedPane();
        LogiIn = new javax.swing.JPanel();
        Login_Label = new javax.swing.JLabel();
        Login_Field = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Password_label = new javax.swing.JPasswordField();
        Register = new javax.swing.JPanel();
        Last_Name = new javax.swing.JTextField();
        First_Name = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        PostCode = new javax.swing.JTextField();
        FirstName_Label = new javax.swing.JLabel();
        LastName_Label = new javax.swing.JLabel();
        City_Label = new javax.swing.JLabel();
        Address_Label = new javax.swing.JLabel();
        PostCode_Label = new javax.swing.JLabel();
        Phone_Number = new javax.swing.JTextField();
        PhoneNumber_Label = new javax.swing.JLabel();
        Sex_Text = new javax.swing.JLabel();
        Sex_box = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pesel_label = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Login_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Email_label = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RePassword_label = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(400, 400));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainPanel.setInheritsPopupMenu(true);
        MainPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        MainPanel.setName(""); // NOI18N
        MainPanel.setPreferredSize(new java.awt.Dimension(500, 100));

        LogiIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogiIn.setMinimumSize(new java.awt.Dimension(500, 200));

        Login_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Login_Label.setText("Login");
        Login_Label.setToolTipText("");

        Login_Field.setText("test Text");
        Login_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_FieldActionPerformed(evt);
            }
        });

        Password_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Password_Label.setText("Password");
        Password_Label.setToolTipText("");

        Login.setText("Login");

        Password_label.setText("jPasswordField1");

        javax.swing.GroupLayout LogiInLayout = new javax.swing.GroupLayout(LogiIn);
        LogiIn.setLayout(LogiInLayout);
        LogiInLayout.setHorizontalGroup(
            LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogiInLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Login_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Login_Label))
                    .addComponent(Password_Label, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Password_label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );
        LogiInLayout.setVerticalGroup(
            LogiInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogiInLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Login_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        MainPanel.addTab("Log In", null, LogiIn, "");

        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.setMinimumSize(new java.awt.Dimension(500, 200));

        Last_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        First_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        First_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_NameActionPerformed(evt);
            }
        });

        City.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        PostCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        FirstName_Label.setText("First Name");

        LastName_Label.setText("City");

        City_Label.setText("Last Name");

        Address_Label.setText("Address");

        PostCode_Label.setText("Post Code");

        Phone_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        PhoneNumber_Label.setText("Phone number");

        Sex_Text.setText("Sex");
        Sex_Text.setToolTipText("");

        Sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female", " " }));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesel");

        Pesel_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel2.setText("Login");

        Login_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel3.setText("E-mail");

        Email_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel4.setText("Password");

        jLabel5.setText("Repeat password");

        RePassword_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(FirstName_Label)
                            .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName_Label)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostCode_Label)
                            .addComponent(PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sex_Text)
                            .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Login_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(City_Label)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Label)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber_Label)
                    .addComponent(Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Pesel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(RePassword_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                        .addComponent(City_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(FirstName_Label)
                        .addGap(2, 2, 2)))
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(First_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastName_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PostCode_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumber_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_Text)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesel_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Login_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RePassword_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        MainPanel.addTab("Register", null, Register, "");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.getAccessibleContext().setAccessibleName("form");
        MainPanel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void First_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_NameActionPerformed

    //Button register
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            //TEST
            System.out.println("Test dzień 999");
            HashMap<String, String> dataFromFile = checkIfDataExist();
            System.out.println("dataFromFile: ");
            System.out.println(dataFromFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
        //String getName, getSurname, city, address, login, password, rePassword, sex;
        //int phoneNumber, pesel, postCode;
        
        name = First_Name.getText();
        surname = Last_Name.getText();
        city = City.getText();
        address = Address.getText();
        login = Login_field.getText();
        password = Password_label.getText();
        rePassword = RePassword_label.getText();
        email = Email_label.getText();
        sex = String.valueOf(Sex_box.getSelectedItem());
        
        phoneNumber = Phone_Number.getText();
        pesel = Pesel_label.getText();
        postCode = PostCode.getText();
        
        person = new Account(name, surname, city, address, login, password, rePassword, sex, email,
                phoneNumber, pesel, postCode);
        
        
        ArrayList<JTextField> accountData = new ArrayList<JTextField>();
            accountData.add(First_Name);
            accountData.add(Last_Name);
            accountData.add(City);
            accountData.add(Address);
            accountData.add(Login_field);
            accountData.add(Password_label);
            accountData.add(RePassword_label);
            accountData.add(Email_label);
            accountData.add(Phone_Number);
            accountData.add(Pesel_label);
            accountData.add(PostCode);
        
        BufferedWriter bf = null;
        
        
        
         //Save data to file
         try{
            JsonObject obj = new JsonObject();
            
            File file = new File(outputFilePath);
            
            obj.addProperty("Name", name);
            obj.addProperty("Surname", surname);
            obj.addProperty("City", city);
            obj.addProperty("Address", address);
            obj.addProperty("Login", login);
            obj.addProperty("Password", password);
            obj.addProperty("Sex", sex);
            obj.addProperty("PhoneNumber", phoneNumber);
            obj.addProperty("Pesel", pesel);
            obj.addProperty("PostCode", postCode);
            
            //check if data are corrected
            checkData(First_Name, Last_Name, City, Address, Login_field, Password_label, RePassword_label, Email_label, Phone_Number, Pesel_label, PostCode);
             
            //check if Login is longer than 8 
            if(login.length() < 8){
                Login_field.setBorder(empty);
            }else{
                Login_field.setBorder(correct);
            }
            
            for(JTextField data : accountData){
                if(data.getBorder() == empty){
                    return;
                }
            }
            
            
            bf = new BufferedWriter(new FileWriter(file, true));
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            //JsonElement account = gson.toJsonTree(person);
            gson.toJson(obj, bf);
            System.out.println("Data Saved!");
            bf.flush();
            //System.out.println("Data saved!");
            

            //file.close();
        }catch(Exception e) {
            System.out.println("ERROR!!!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public  HashMap<String, String> checkIfDataExist() throws FileNotFoundException{
        System.out.println("DZIAŁA!");
        //Gson gson = new Gson();
            System.out.println("1");
            BufferedReader bufferedReader = new BufferedReader(new FileReader(outputFilePath));
System.out.println("2");
            Gson gson = new Gson();
            System.out.println("3");
            HashMap<String, String> json = gson.fromJson(bufferedReader, HashMap.class);
            System.out.println("file data: ");
            System.out.println(json);
            return json;
        
    }
    
    
    private void Login_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_FieldActionPerformed

    public void checkData(JTextField name, JTextField surname, JTextField city, JTextField address, JTextField login, 
            JTextField password, JTextField rePassword, JTextField email, JTextField phoneNumber, JTextField pesel, JTextField postCode){
            //Border empty = BorderFactory.createLineBorder(Color.RED, 1);
            //Border correct = BorderFactory.createLineBorder(Color.gray, 1);

            ArrayList<JTextField> accountData = new ArrayList<JTextField>();
            accountData.add(name);
            accountData.add(surname);
            accountData.add(city);
            accountData.add(address);
            accountData.add(login);
            accountData.add(password);
            accountData.add(rePassword);
            accountData.add(email);
            accountData.add(phoneNumber);
            accountData.add(pesel);
            accountData.add(postCode);
            
            
            //Check if field is empty
            for(JTextField data : accountData){
                if(data.getText().isEmpty()){
                    data.setBorder(empty);
                }else{
                    data.setBorder(correct);
                }
            }
            
            //check if Pesel contains only numbers and length is equal 11
            isDigit(pesel, 11);
            
            //check if phone number contains only numbers and length is equal 9
            isDigit(phoneNumber, 9);
            
            //check if password is the same like rePassword
            if(!password.getText().equals(rePassword.getText())){
                password.setBorder(empty);
                rePassword.setBorder(empty);
            }else{
                password.setBorder(correct);
                rePassword.setBorder(correct);
            }
            
            //check if password contain one special char, one big letter, one digit and is longer than 8
            checkPassword(password);

           
            
    }
    
    public boolean checkPassword(JTextField password){
        boolean upperCase = false;
        boolean lowerCase = false;
        boolean digit = false;
        boolean specialChar = false;
        
        String text = password.getText();
        
        if(text.length() < 8){
            return false;
        }
        
        for(int i = 0; i < text.length(); ++i){
            if(Character.isDigit(text.charAt(i))){
                digit = true;
            }
            if(Character.isUpperCase(text.charAt(i))){
                upperCase = true;
            }
            if(Character.isLowerCase(text.charAt(i))){
                lowerCase = true;
            }
            if(!Character.isDigit(text.charAt(i))
               && !Character.isLetter(text.charAt(i))
               && !Character.isWhitespace(text.charAt(i))){
               
                specialChar = true;           
            }
        }
        
        
        if(upperCase && digit && specialChar && lowerCase){
            password.setBorder(correct);
            return true;
        }else{
            password.setBorder(empty);
            return false;
        }
    }
    
    
    // Method allow to check if every char in str is digit and length of str is equal length
    public void isDigit(JTextField str, int length){
        if(str.getText().length() !=  length){
                str.setBorder(empty);
            }else{
                str.setBorder(correct);
            }
            for(int i = 0; i < str.getText().length(); ++i){
                char checkChar = str.getText().charAt(i);
                if(!Character.isDigit(checkChar)){
                    str.setBorder(empty);
                }
            }
    }
    
   
    public void createGUI(){
        F.setMinimumSize(new Dimension(500,500));
        F.setPreferredSize(new Dimension(500,500));
        F.add(MainPanel);
        F.setVisible(true);
        String getName = Login_Field.getText();
        System.out.println("Text: " + getName);
    }
    
   
   
    public static void main(String[] args) {
        
        Gson gson = new Gson();
        NewJPanel N = new NewJPanel();
        N.setPreferredSize(new Dimension(500,500));
        //N.setMinimumSize(new Dimension(650,470));
        N.createGUI();
        
       

        
        
        //String getName, getSurname, city, address, login, password, rePassword, sex;
        //int phoneNumber, pesel, postCode;
        
        
        
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Address_Label;
    private javax.swing.JTextField City;
    private javax.swing.JLabel City_Label;
    private javax.swing.JTextField Email_label;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField First_Name;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JPanel LogiIn;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Login_Field;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JTextField Login_field;
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JPasswordField Password_label;
    private javax.swing.JTextField Pesel_label;
    private javax.swing.JLabel PhoneNumber_Label;
    private javax.swing.JTextField Phone_Number;
    private javax.swing.JTextField PostCode;
    private javax.swing.JLabel PostCode_Label;
    private javax.swing.JTextField RePassword_label;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel Sex_Text;
    private javax.swing.JComboBox<String> Sex_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}

/*

        name = First_Name.getText();                    JTextField
        surname = Last_Name.getText();                  JTextField
        city = City.getText();                          JTextField
        address = Address.getText();                    JTextField
        login = Login_field.getText();                  JTextField
        password = Password_label.getText();            JTextField
        rePassword = RePassword_label.getText();        JTextField
        
        phoneNumber = Phone_Number.getText();           JTextField
        pesel = Pesel_label.getText();                  JTextField
        postCode = PostCode.getText();                  JTextField  

*/